name: Deploy sanity studio
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Restore cached Node Modules 💾
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
<<<<<<< HEAD:.github/workflows/main.yml
      - name: Deploy Studio
        run: npm run deploy
=======

      - name: Build and deploy
        run: npm run deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}  # Set the Sanity auth token as an environment variable
          BRANCH: gh-pages  # Set the branch name for GitHub Pages
          FOLDER: public  # Set the folder name for the built Sanity Studio
>>>>>>> 6edbe992c0c2d8cf805adf53c382bf0609e92db1:.github/workflows/deploy-sanity.yml
